%YAML:1.0

# Topics
radar_topic: "/mmWaveDataHdl/RScan" # Point cloud data <!-- pc2_raw inlier_pc2 segmented -->
imu_topic: "/gx5/imu/data" #IMU data

# RISE Init Cov Settings
Pos: 0.0 
Vel: 1.0e-03
RollPitch: 1.0e-06 
Yaw: 1.0e-06 
BiasGyr: 1.0e-06 
BiasAcc: 1.0e-03 
RotExt: 1.0e-08
PosExt: 1.0e-08

# IMU Settings
imuAccNoise: 0.0023454  
imuGyrNoise: 0.00087306 
imuAccBias: 0.0 
imuGyrBias: 0.00186168 
imuGravity: 9.796 #9.796
imuInitVel: 0.01 

# 4dRadar Settings
rangeCov: 0.05       #m   resolution 0.12 
azimuthCov: 0.5      #deg resolution 1 
elevationCov: 10.0    #deg resolution 22.5 
dopplerCov: 0.10     #m/s resolution 0.25  #0.10  #0.20(w/o WD)
PointUpdateTh: 0.85   #percent #0.85 #1.0(w/o UP)

# Filter Settings
minRange: 0.5
maxRange: 15.0
maxDoppler: 0.05
minIntensity: 0.20 
NeighborRange: -1.0
NeighborNum: 0.0
NeighborStd: 0.0

# NDT Settings
max_iteration: 10   #10  #3(w/o JU)
voxel_size: 0.5    #0.5 #0.75(w/o WD)
eps: 0.0001    
res_outlier_th: 1.0   #1.0
dop_outlier_th: 0.4  #0.4 #0.85(w/o WF)
capacity: 3000    
kf_distance: 0.3     
kf_angle_deg: 5     
kf_frame: 10     

# Calibs
T_Radar_to_Imu: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [ 0.99999995, 0.00079265,  0.00059265,  0.02995821,
           0.00079265, -0.99999969,  0.00000000, 0.12002374,
          -0.00059265, 0.00000047, -0.99999982,  -0.08998226,
           0.00000000, 0.00000000,  0.00000000,  1.00000000]